# Generated by Django 5.1.2 on 2024-10-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_nickname',
            field=models.CharField(blank=True, help_text='Укажите ник в Телеграм', max_length=55, null=True, verbose_name='TG user name'),
        ),
    ]
