# Generated by Django 5.1.2 on 2024-10-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tg_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите TG chat id', max_length=55, null=True, verbose_name='TG chat id'),
        ),
    ]
