# Generated by Django 5.1.2 on 2024-10-09 18:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_place', models.CharField(blank=True, help_text='Укажите место действия', max_length=155, null=True, verbose_name='Место действия')),
                ('action_time_for', models.TimeField(blank=True, help_text='Укажите время, когда необходимо выполнять привычку', null=True, verbose_name='Время начала выполнения привычки')),
                ('action', models.CharField(blank=True, help_text='Действие, которое представляет собой привычка', max_length=255, null=True, verbose_name='Действие')),
                ('periodic', models.SmallIntegerField(blank=True, default=1, help_text='Укажите периодичность выполнения привычки в днях', null=True, verbose_name='Периодичность')),
                ('action_duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=120), help_text='Укажите продолжительность выполнения привычки в минутах', null=True, verbose_name='Продолжительность')),
                ('prize_action', models.CharField(blank=True, help_text='Действие, которое представляет собой вознаграждение', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('is_useful', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('is_published', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите Создателя привычки', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('related_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
