# Generated by Django 5.1.2 on 2024-10-12 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_habit_is_useful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action_duration',
            field=models.DurationField(blank=True, help_text='Укажите продолжительность выполнения привычки в минутах', null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Продолжительность'),
        ),
    ]
