# Generated by Django 5.1.2 on 2024-10-12 19:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_action_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=120), help_text='Укажите продолжительность выполнения привычки в минутах', null=True, validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120))], verbose_name='Продолжительность'),
        ),
    ]
