# Generated by Django 5.1.2 on 2024-10-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_action_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='action_time_for',
            new_name='action_time',
        ),
    ]
