# Generated by Django 5.1.2 on 2024-10-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_rename_action_time_for_habit_action_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='action_datetime',
            field=models.DateTimeField(blank=True, help_text='Укажите время, когда необходимо выполнять привычку', null=True, verbose_name='Дата/Время циклического выполнения привычки'),
        ),
    ]
